name       : haskell-microlens
version    : 0.4.11.2
release    : 3
source     :
    - https://hackage.haskell.org/package/microlens-0.4.11.2/microlens-0.4.11.2.tar.gz : 4e484d4a73c7c5176ccfdacc29aec7399352cac1c7e8924d5123857cf36ddffc
license    : BSD-3-Clause
component  : programming.haskell
summary    : This library is an extract from lens (with no dependencies). It's not a toy lenses library, unsuitable for “real world”, but merely a small one. It is compatible with lens, and should have same performance. It also has better documentation.
description: |
    This library is an extract from lens (with no dependencies). It's not a toy lenses library, unsuitable for “real world”, but merely a small one. It is compatible with lens, and should have same performance. It also has better documentation.
builddeps  :
    - ghc-devel
    - haskell-cabal-install
rundeps    :
    - devel:
        - ghc-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
