name       : haskell-microlens
version    : 0.4.9.1
release    : 2
source     :
    - https://hackage.haskell.org/package/microlens-0.4.9.1/microlens-0.4.9.1.tar.gz : a1401c6f92c142bafea4cf58a1d99cc34af285df808b97f5b64af4bb81fb5648
license    : BSD-3-Clause
component  : programming.haskell
summary    : This library is an extract from lens (with no dependencies). It's not a toy lenses library, unsuitable for “real world”, but merely a small one. It is compatible with lens, and should have
    same performance. It also has better documentation.
description: |
    This library is an extract from lens (with no dependencies). It's not a toy lenses library, unsuitable for “real world”, but merely a small one. It is compatible with lens, and should have same performance. It also has better documentation.
builddeps  :
    - ghc
    - haskell-cabal-install
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
